### ISSUE TITLE
Any reference for minNormSolver?

### ISSUE THREAD

**Issue by twmht** [hav4ik/Hydra#1]
Is there any reference or algorithm did you use for implementing MinNormSolver?

**Comment by hav4ik** [comment]
Hi, this is the reference paper: https://arxiv.org/pdf/1810.04650v2.pdf
The reference implementation is here: https://github.com/intel-isl/MultiObjectiveOptimization/blob/master/multi_task/min_norm_solvers.py

However, if you look closer to the reference implementation -- it is very slow! It heavily relies on passing objects back and forth between RAM and GPU memory. Moreover, the authors used **for loops** in python which is absolutely terrible in terms of speed performance.

My implementation (https://github.com/hav4ik/Hydra/blob/master/src/utils/min_norm_solver.py) is a vectorized version of it. It is executed only in GPU and is vectorized (hence everything works in parallel, no for loops)
